server:
  port: '8000'

spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://172.21.100.233:5432/appdb
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      formate_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
      default_schema: public
    show-sql: 'true'
secrets:
  dbconfig: /mnt/d/Workspace/Vault/dbsecrets.json
---
