server:
  port: '8000'

spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    username: ${ENV_DB_USER}
    password: ${ENV_DB_PASSWD}
    url: jdbc:mysql://localhost:3306/dcbapp
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
ui:
  msg1: welcome to milkyway galaxy!!
  msg2: my nearest friend is andromeda!!
  msg3: ${ENV_MSG}
---
