server:
  port: 8000
spring:
  profiles:
    active: dev
---

spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/hellodb
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to CRUD Demo Application - dev!!
management:
  endpoints:
    web:
      exposure:
        include: "*"
---

spring:
  profiles: qa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/hellodb
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to CRUD Demo Application - qa!!
management:
  endpoints:
    web:
      exposure:
        include: "*"

---

spring:
  profiles: stage
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/hellodb
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to CRUD Demo Application - stage!!
management:
  endpoints:
    web:
      exposure:
        include: "*"

---

spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/hellodb
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to CRUD Demo Application - prod!!
management:
  endpoints:
    web:
      exposure:
        include: "*"
